import type { LogisticsInfo, SellerLogisticsInfoResult } from '../typings/types'

const unsortedSellersMock = [
  {
    seller: {
      sellerId: '1',
      sellerName: 'SELLER NAME 1',
      sellerDefault: false,
      addToCartLink: '',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 280.5,
        ListPrice: 280.5,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 280.5,
        PriceWithoutDiscount: 280.5,
        RewardValue: 0,
        PriceValidUntil: '2022-08-25T13:35:42Z',
        AvailableQuantity: 6000,
        CacheVersionUsedToCallCheckout: 'B2D78F230C87C13044F23B4A0F4BA986_',
        Installments: [],
      },
    },
    logisticsInfo: {} as LogisticsInfo,
  },
  {
    seller: {
      sellerId: '2',
      sellerName: 'SELLER NAME 2',
      sellerDefault: true,
      addToCartLink: '',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 100,
        ListPrice: 100,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 100,
        PriceWithoutDiscount: 100,
        RewardValue: 0,
        PriceValidUntil: '2022-08-25T13:35:41Z',
        AvailableQuantity: 992,
        CacheVersionUsedToCallCheckout: 'B2D78F230C87C13044F23B4A0F4BA986_',
        Installments: [],
      },
    },
    logisticsInfo: {} as LogisticsInfo,
  },
  {
    seller: {
      sellerId: '3',
      sellerName: 'SELLER NAME 3',
      sellerDefault: false,
      addToCartLink: '',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 1,
        ListPrice: 1,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 1,
        PriceWithoutDiscount: 1,
        RewardValue: 0,
        PriceValidUntil: '2022-08-25T13:35:42Z',
        AvailableQuantity: 6000,
        CacheVersionUsedToCallCheckout: 'B2D78F230C87C13044F23B4A0F4BA986_',
        Installments: [],
      },
    },
    logisticsInfo: {} as LogisticsInfo,
  },
  {
    seller: {
      sellerId: '4',
      sellerName: 'SELLER NAME 4',
      sellerDefault: true,
      addToCartLink: '',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 25,
        ListPrice: 25,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 25,
        PriceWithoutDiscount: 25,
        RewardValue: 0,
        PriceValidUntil: '2022-08-25T13:35:41Z',
        AvailableQuantity: 992,
        CacheVersionUsedToCallCheckout: 'B2D78F230C87C13044F23B4A0F4BA986_',
        Installments: [],
      },
    },
    logisticsInfo: {} as LogisticsInfo,
  },
  {
    seller: {
      sellerId: '5',
      sellerName: 'SELLER NAME 5',
      sellerDefault: false,
      addToCartLink: '',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 15,
        ListPrice: 15,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 15,
        PriceWithoutDiscount: 15,
        RewardValue: 0,
        PriceValidUntil: '2022-08-25T13:35:42Z',
        AvailableQuantity: 6000,
        CacheVersionUsedToCallCheckout: 'B2D78F230C87C13044F23B4A0F4BA986_',
        Installments: [],
      },
    },
    logisticsInfo: {} as LogisticsInfo,
  },
  {
    seller: {
      sellerId: '6',
      sellerName: 'SELLER NAME 6',
      sellerDefault: true,
      addToCartLink: '',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 80,
        ListPrice: 80,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 80,
        PriceWithoutDiscount: 80,
        RewardValue: 0,
        PriceValidUntil: '2022-08-25T13:35:41Z',
        AvailableQuantity: 992,
        CacheVersionUsedToCallCheckout: 'B2D78F230C87C13044F23B4A0F4BA986_',
        Installments: [],
      },
    },
    logisticsInfo: {} as LogisticsInfo,
  },
] as SellerLogisticsInfoResult[]

const unsortedSellersShippingMock = [
  {
    seller: {
      sellerId: '1',
      sellerName: 'SELLER NAME 1',
      sellerDefault: false,
      addToCartLink: '',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 280.5,
        ListPrice: 280.5,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 280.5,
        PriceWithoutDiscount: 280.5,
        RewardValue: 0,
        PriceValidUntil: '2022-08-25T13:35:42Z',
        AvailableQuantity: 6000,
        CacheVersionUsedToCallCheckout: 'B2D78F230C87C13044F23B4A0F4BA986_',
        Installments: [],
      },
    },
    logisticsInfo: {
      itemIndex: 1,
      slas: [
        {
          id: '1',
          name: 'logistic name',
          price: 4000,
          shippingEstimate: '8bd',
          shippingEstimateDate: '',
        },
      ],
    } as LogisticsInfo,
  },
  {
    seller: {
      sellerId: '2',
      sellerName: 'SELLER NAME 2',
      sellerDefault: true,
      addToCartLink: '',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 100,
        ListPrice: 100,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 100,
        PriceWithoutDiscount: 100,
        RewardValue: 0,
        PriceValidUntil: '2022-08-25T13:35:41Z',
        AvailableQuantity: 992,
        CacheVersionUsedToCallCheckout: 'B2D78F230C87C13044F23B4A0F4BA986_',
        Installments: [],
      },
    },
    logisticsInfo: {
      itemIndex: 1,
      slas: [
        {
          id: '1',
          name: 'logistic name',
          price: 8000,
          shippingEstimate: '4d',
          shippingEstimateDate: '',
        },
      ],
    } as LogisticsInfo,
  },
  {
    seller: {
      sellerId: '3',
      sellerName: 'SELLER NAME 3',
      sellerDefault: false,
      addToCartLink: '',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 1,
        ListPrice: 1,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 1,
        PriceWithoutDiscount: 1,
        RewardValue: 0,
        PriceValidUntil: '2022-08-25T13:35:42Z',
        AvailableQuantity: 6000,
        CacheVersionUsedToCallCheckout: 'B2D78F230C87C13044F23B4A0F4BA986_',
        Installments: [],
      },
    },
    logisticsInfo: {
      itemIndex: 1,
      slas: [],
    } as LogisticsInfo,
  },
  {
    seller: {
      sellerId: '4',
      sellerName: 'SELLER NAME 4',
      sellerDefault: true,
      addToCartLink: '',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 25,
        ListPrice: 25,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 25,
        PriceWithoutDiscount: 25,
        RewardValue: 0,
        PriceValidUntil: '2022-08-25T13:35:41Z',
        AvailableQuantity: 992,
        CacheVersionUsedToCallCheckout: 'B2D78F230C87C13044F23B4A0F4BA986_',
        Installments: [],
      },
    },
  },
  {
    seller: {
      sellerId: '5',
      sellerName: 'SELLER NAME 5',
      sellerDefault: false,
      addToCartLink: '',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 15,
        ListPrice: 15,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 15,
        PriceWithoutDiscount: 15,
        RewardValue: 0,
        PriceValidUntil: '2022-08-25T13:35:42Z',
        AvailableQuantity: 6000,
        CacheVersionUsedToCallCheckout: 'B2D78F230C87C13044F23B4A0F4BA986_',
        Installments: [],
      },
    },
    logisticsInfo: {
      itemIndex: 1,
      slas: [
        {
          id: '1',
          name: 'logistic name 1',
          price: 4000,
          shippingEstimate: '3d',
          shippingEstimateDate: '',
        },
        {
          id: '2',
          name: 'logistic name 2',
          price: 9000,
          shippingEstimate: '1h',
          shippingEstimateDate: '',
        },
      ],
    } as LogisticsInfo,
  },
  {
    seller: {
      sellerId: '6',
      sellerName: 'SELLER NAME 6',
      sellerDefault: true,
      addToCartLink: '',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 80,
        ListPrice: 80,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 80,
        PriceWithoutDiscount: 80,
        RewardValue: 0,
        PriceValidUntil: '2022-08-25T13:35:41Z',
        AvailableQuantity: 992,
        CacheVersionUsedToCallCheckout: 'B2D78F230C87C13044F23B4A0F4BA986_',
        Installments: [],
      },
    },
    logisticsInfo: {
      itemIndex: 1,
      slas: [
        {
          id: '1',
          name: 'logistic name',
          price: 0,
          shippingEstimate: '8bd',
          shippingEstimateDate: '',
        },
        {
          id: '1',
          name: 'logistic name',
          price: 2000,
          shippingEstimate: '30m',
          shippingEstimateDate: '',
        },
      ],
    } as LogisticsInfo,
  },
] as SellerLogisticsInfoResult[]

const unsortedSellerLogisticsInfoMock = [
  {
    seller: {
      sellerId: 'rjriodejaneirocasashopping099',
      sellerName: 'Loja IWS - Casa Shopping (RJ)',
      sellerDefault: true,
      addToCartLink:
        'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=240&qty=1&seller=rjriodejaneirocasashopping099&sc=1&price=8990&cv=E856A167161640718AB90DD345A81A7E_&sc=1',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 89.9,
        ListPrice: 89.9,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 89.9,
        PriceWithoutDiscount: 89.9,
        RewardValue: 0,
        PriceValidUntil: '2023-07-29T13:35:37Z',
        AvailableQuantity: 2,
        CacheVersionUsedToCallCheckout: 'E856A167161640718AB90DD345A81A7E_',
        Installments: [],
      },
    },
    logisticsInfo: {
      itemIndex: 0,
      slas: [
        {
          id: 'PAC',
          name: 'PAC',
          price: 0,
          shippingEstimate: '6bd',
          shippingEstimateDate: '',
        },
        {
          id: 'SEDEX',
          name: 'SEDEX',
          price: 3188,
          shippingEstimate: '2bd',
          shippingEstimateDate: '',
        },
      ],
    },
  },
  {
    seller: {
      sellerId: 'lojaiwslourdesbh573',
      sellerName: 'Loja IWS - Lourdes (BH)',
      sellerDefault: false,
      addToCartLink:
        'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=240&qty=1&seller=lojaiwslourdesbh573&sc=1&price=8990&cv=E856A167161640718AB90DD345A81A7E_&sc=1',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 89.9,
        ListPrice: 89.9,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 89.9,
        PriceWithoutDiscount: 89.9,
        RewardValue: 0,
        PriceValidUntil: '2023-07-29T13:35:37Z',
        AvailableQuantity: 3,
        CacheVersionUsedToCallCheckout: 'E856A167161640718AB90DD345A81A7E_',
        Installments: [],
      },
    },
    logisticsInfo: {
      itemIndex: 1,
      slas: [
        {
          id: 'Correios - PAC',
          name: 'Correios - PAC',
          price: 0,
          shippingEstimate: '6bd',
          shippingEstimateDate: '',
        },
        {
          id: 'Correios - SEDEX',
          name: 'Correios - SEDEX',
          price: 3180,
          shippingEstimate: '2bd',
          shippingEstimateDate: '',
        },
      ],
    },
  },
  {
    seller: {
      sellerId: 'lojaiwscampinassp719',
      sellerName: 'Loja IWS - Campinas (SP)',
      sellerDefault: false,
      addToCartLink:
        'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=240&qty=1&seller=lojaiwscampinassp719&sc=1&price=8990&cv=E856A167161640718AB90DD345A81A7E_&sc=1',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 89.9,
        ListPrice: 89.9,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 89.9,
        PriceWithoutDiscount: 89.9,
        RewardValue: 0,
        PriceValidUntil: '2023-07-29T13:35:37Z',
        AvailableQuantity: 4,
        CacheVersionUsedToCallCheckout: 'E856A167161640718AB90DD345A81A7E_',
        Installments: [],
      },
    },
    logisticsInfo: {
      itemIndex: 2,
      slas: [
        {
          id: 'Correios - SEDEX',
          name: 'Correios - SEDEX',
          price: 0,
          shippingEstimate: '2bd',
          shippingEstimateDate: '',
        },
      ],
    },
  },
  {
    seller: {
      sellerId: 'lojaiwssilvianobrandaobh935',
      sellerName: 'Loja IWS - Silviano Brandão (BH)',
      sellerDefault: false,
      addToCartLink:
        'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=240&qty=1&seller=lojaiwssilvianobrandaobh935&sc=1&price=8990&cv=E856A167161640718AB90DD345A81A7E_&sc=1',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 89.9,
        ListPrice: 89.9,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 89.9,
        PriceWithoutDiscount: 89.9,
        RewardValue: 0,
        PriceValidUntil: '2023-07-29T13:35:37Z',
        AvailableQuantity: 5,
        CacheVersionUsedToCallCheckout: 'E856A167161640718AB90DD345A81A7E_',
        Installments: [],
      },
    },
    logisticsInfo: {
      itemIndex: 3,
      slas: [
        {
          id: 'Correios - PAC',
          name: 'Correios - PAC',
          price: 0,
          shippingEstimate: '6bd',
          shippingEstimateDate: '',
        },
        {
          id: 'Correios - SEDEX',
          name: 'Correios - SEDEX',
          price: 3180,
          shippingEstimate: '2bd',
          shippingEstimateDate: '',
        },
      ],
    },
  },
  {
    seller: {
      sellerId: 'lojaiwscampograndems217',
      sellerName: 'Loja IWS - Campo Grande (MS)',
      sellerDefault: false,
      addToCartLink:
        'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=240&qty=1&seller=lojaiwscampograndems217&sc=1&price=8990&cv=E856A167161640718AB90DD345A81A7E_&sc=1',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 89.9,
        ListPrice: 89.9,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 89.9,
        PriceWithoutDiscount: 89.9,
        RewardValue: 0,
        PriceValidUntil: '2023-07-29T13:35:37Z',
        AvailableQuantity: 1,
        CacheVersionUsedToCallCheckout: 'E856A167161640718AB90DD345A81A7E_',
        Installments: [],
      },
    },
    logisticsInfo: {
      itemIndex: 4,
      slas: [
        {
          id: 'Correios - PAC',
          name: 'Correios - PAC',
          price: 0,
          shippingEstimate: '7bd',
          shippingEstimateDate: '',
        },
        {
          id: 'Correios - SEDEX',
          name: 'Correios - SEDEX',
          price: 4416,
          shippingEstimate: '2bd',
          shippingEstimateDate: '',
        },
      ],
    },
  },
] as SellerLogisticsInfoResult[]

const sortedSellerLogisticsInfoMock = [
  {
    seller: {
      sellerId: 'lojaiwscampinassp719',
      sellerName: 'Loja IWS - Campinas (SP)',
      sellerDefault: true,
      addToCartLink:
        'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=240&qty=1&seller=lojaiwscampinassp719&sc=1&price=8990&cv=E856A167161640718AB90DD345A81A7E_&sc=1',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 89.9,
        ListPrice: 89.9,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 89.9,
        PriceWithoutDiscount: 89.9,
        RewardValue: 0,
        PriceValidUntil: '2023-07-29T13:35:37Z',
        AvailableQuantity: 4,
        CacheVersionUsedToCallCheckout: 'E856A167161640718AB90DD345A81A7E_',
        Installments: [],
      },
    },
    logisticsInfo: {
      itemIndex: 2,
      slas: [
        {
          id: 'Correios - SEDEX',
          name: 'Correios - SEDEX',
          price: 0,
          shippingEstimate: '2bd',
          shippingEstimateDate: '',
        },
      ],
    },
  },
  {
    seller: {
      sellerId: 'lojaiwslourdesbh573',
      sellerName: 'Loja IWS - Lourdes (BH)',
      sellerDefault: false,
      addToCartLink:
        'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=240&qty=1&seller=lojaiwslourdesbh573&sc=1&price=8990&cv=E856A167161640718AB90DD345A81A7E_&sc=1',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 89.9,
        ListPrice: 89.9,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 89.9,
        PriceWithoutDiscount: 89.9,
        RewardValue: 0,
        PriceValidUntil: '2023-07-29T13:35:37Z',
        AvailableQuantity: 3,
        CacheVersionUsedToCallCheckout: 'E856A167161640718AB90DD345A81A7E_',
        Installments: [],
      },
    },
    logisticsInfo: {
      itemIndex: 1,
      slas: [
        {
          id: 'Correios - SEDEX',
          name: 'Correios - SEDEX',
          price: 3180,
          shippingEstimate: '2bd',
          shippingEstimateDate: '',
        },
        {
          id: 'Correios - PAC',
          name: 'Correios - PAC',
          price: 0,
          shippingEstimate: '6bd',
          shippingEstimateDate: '',
        },
      ],
    },
  },
  {
    seller: {
      sellerId: 'lojaiwssilvianobrandaobh935',
      sellerName: 'Loja IWS - Silviano Brandão (BH)',
      sellerDefault: false,
      addToCartLink:
        'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=240&qty=1&seller=lojaiwssilvianobrandaobh935&sc=1&price=8990&cv=E856A167161640718AB90DD345A81A7E_&sc=1',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 89.9,
        ListPrice: 89.9,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 89.9,
        PriceWithoutDiscount: 89.9,
        RewardValue: 0,
        PriceValidUntil: '2023-07-29T13:35:37Z',
        AvailableQuantity: 5,
        CacheVersionUsedToCallCheckout: 'E856A167161640718AB90DD345A81A7E_',
        Installments: [],
      },
    },
    logisticsInfo: {
      itemIndex: 3,
      slas: [
        {
          id: 'Correios - SEDEX',
          name: 'Correios - SEDEX',
          price: 3180,
          shippingEstimate: '2bd',
          shippingEstimateDate: '',
        },
        {
          id: 'Correios - PAC',
          name: 'Correios - PAC',
          price: 0,
          shippingEstimate: '6bd',
          shippingEstimateDate: '',
        },
      ],
    },
  },
  {
    seller: {
      sellerId: 'rjriodejaneirocasashopping099',
      sellerName: 'Loja IWS - Casa Shopping (RJ)',
      sellerDefault: false,
      addToCartLink:
        'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=240&qty=1&seller=rjriodejaneirocasashopping099&sc=1&price=8990&cv=E856A167161640718AB90DD345A81A7E_&sc=1',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 89.9,
        ListPrice: 89.9,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 89.9,
        PriceWithoutDiscount: 89.9,
        RewardValue: 0,
        PriceValidUntil: '2023-07-29T13:35:37Z',
        AvailableQuantity: 2,
        CacheVersionUsedToCallCheckout: 'E856A167161640718AB90DD345A81A7E_',
        Installments: [],
      },
    },
    logisticsInfo: {
      itemIndex: 0,
      slas: [
        {
          id: 'SEDEX',
          name: 'SEDEX',
          price: 3188,
          shippingEstimate: '2bd',
          shippingEstimateDate: '',
        },
        {
          id: 'PAC',
          name: 'PAC',
          price: 0,
          shippingEstimate: '6bd',
          shippingEstimateDate: '',
        },
      ],
    },
  },
  {
    seller: {
      sellerId: 'lojaiwscampograndems217',
      sellerName: 'Loja IWS - Campo Grande (MS)',
      sellerDefault: false,
      addToCartLink:
        'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=240&qty=1&seller=lojaiwscampograndems217&sc=1&price=8990&cv=E856A167161640718AB90DD345A81A7E_&sc=1',
      commertialOffer: {
        discountHighlights: [],
        teasers: [],
        Price: 89.9,
        ListPrice: 89.9,
        Tax: 0,
        taxPercentage: 0,
        spotPrice: 89.9,
        PriceWithoutDiscount: 89.9,
        RewardValue: 0,
        PriceValidUntil: '2023-07-29T13:35:37Z',
        AvailableQuantity: 1,
        CacheVersionUsedToCallCheckout: 'E856A167161640718AB90DD345A81A7E_',
        Installments: [],
      },
    },
    logisticsInfo: {
      itemIndex: 4,
      slas: [
        {
          id: 'Correios - SEDEX',
          name: 'Correios - SEDEX',
          price: 4416,
          shippingEstimate: '2bd',
          shippingEstimateDate: '',
        },
        {
          id: 'Correios - PAC',
          name: 'Correios - PAC',
          price: 0,
          shippingEstimate: '7bd',
          shippingEstimateDate: '',
        },
      ],
    },
  },
] as SellerLogisticsInfoResult[]

export {
  unsortedSellersMock,
  unsortedSellersShippingMock,
  unsortedSellerLogisticsInfoMock,
  sortedSellerLogisticsInfoMock,
}
